import type { Offer, StudentProfile, Match } from "./storage";

export const DEMO_STUDENT_PROFILE: StudentProfile = {
  firstName: "Léa",
  lastName: "Martin",
  gender: "F",
  dateOfBirth: "2002-03-15",
  phone: "+33 6 12 34 56 78",
  address: "15 Cours du Médoc, 33300 Bordeaux",
  latitude: 44.8588,
  longitude: -0.5733,
  diploma: "Licence 2 — Droit",
  school: "Université de Bordeaux",
  skills: ["Accueil", "Service en salle", "Vente"],
  jobTypes: ["Restauration", "Commerce"],
  availabilities: {
    vendredi: { matin: false, aprem: false, soir: true },
    samedi: { matin: true, aprem: true, soir: true },
    dimanche: { matin: true, aprem: true, soir: false },
  },
  bio: "Étudiante en droit passionnée par le contact client. Je cherche des missions flexibles pour financer mes études tout en acquérant une expérience professionnelle.",
  iban: null,
  bic: null,
  photoUrl: null,
  cvUrl: null,
};

export const DEMO_STUDENT_MATCHES: Match[] = [
  // ── Visible in chat / candidatures ──────────────────────────────────────
  {
    id: "demo-match-1",
    offerId: "demo-1",
    offerTitle: "Serveur / Serveuse",
    companyName: "Bistrot des Chartrons",
    logoUrl: null,
    status: "ACCEPTE",
    score: 89,
    appliedAt: "2026-05-19T10:00:00.000Z",
  },
  {
    id: "demo-match-2",
    offerId: "demo-2",
    offerTitle: "Vendeur(se) en boutique",
    companyName: "Mode & Style",
    logoUrl: null,
    status: "PENDING",
    score: 72,
    appliedAt: "2026-05-18T14:00:00.000Z",
  },
  {
    id: "demo-match-3",
    offerId: "demo-4",
    offerTitle: "Livreur(se) à vélo",
    companyName: "VéloGironde",
    logoUrl: null,
    status: "REFUSE",
    score: 58,
    appliedAt: "2026-05-17T09:00:00.000Z",
  },
  // ── Past accepted missions (calendar dots) ───────────────────────────────
  {
    id: "demo-match-4",
    offerId: "demo-3",
    offerTitle: "Agent de sécurité événementiel",
    companyName: "Sécur'Events",
    logoUrl: null,
    status: "ACCEPTE",
    score: 81,
    appliedAt: "2026-05-10T10:00:00.000Z",
  },
  {
    id: "demo-match-5",
    offerId: "demo-5",
    offerTitle: "Commis de cuisine",
    companyName: "La Brasserie du Port",
    logoUrl: null,
    status: "ACCEPTE",
    score: 76,
    appliedAt: "2026-05-03T10:00:00.000Z",
  },
  {
    id: "demo-match-6",
    offerId: "demo-1",
    offerTitle: "Serveur / Serveuse",
    companyName: "Bistrot des Chartrons",
    logoUrl: null,
    status: "ACCEPTE",
    score: 89,
    appliedAt: "2026-04-26T10:00:00.000Z",
  },
  // ── Future accepted missions (calendar dots) ─────────────────────────────
  {
    id: "demo-match-7",
    offerId: "demo-1",
    offerTitle: "Serveur / Serveuse",
    companyName: "Bistrot des Chartrons",
    logoUrl: null,
    status: "ACCEPTE",
    score: 89,
    appliedAt: "2026-05-24T10:00:00.000Z",
  },
  {
    id: "demo-match-8",
    offerId: "demo-3",
    offerTitle: "Agent de sécurité événementiel",
    companyName: "Sécur'Events",
    logoUrl: null,
    status: "ACCEPTE",
    score: 81,
    appliedAt: "2026-06-07T10:00:00.000Z",
  },
  {
    id: "demo-match-9",
    offerId: "demo-5",
    offerTitle: "Commis de cuisine",
    companyName: "La Brasserie du Port",
    logoUrl: null,
    status: "ACCEPTE",
    score: 76,
    appliedAt: "2026-06-14T10:00:00.000Z",
  },
];

export const DEMO_OFFERS: Offer[] = [
  {
    id: "demo-1",
    title: "Serveur / Serveuse",
    description:
      "Nous recherchons un(e) serveur(se) dynamique pour renforcer notre équipe le week-end. Vous assurez l'accueil des clients, la prise de commandes et le service en salle dans notre bistrot bordelais.",
    location: "16 Rue des Bahutiers, 33000 Bordeaux",
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    hourlyRate: 12.00,
    nbPositions: 2,
    latitude: 44.8384,
    longitude: -0.5717,
    requiredSkills: ["Service en salle", "Accueil"],
    schedules: {
      vendredi: { start: "18:00", end: "23:00" },
      samedi: { start: "12:00", end: "23:00" },
      dimanche: { start: "12:00", end: "17:00" },
    },
    jobType: "Restauration",
    status: "ACTIVE",
    companyName: "Bistrot des Chartrons",
    logoUrl: null,
    activityType: "RESTAURATION",
    isDemo: true,
  },
  {
    id: "demo-2",
    title: "Vendeur(se) en boutique",
    description:
      "Pour notre boutique de prêt-à-porter, nous cherchons un(e) vendeur(se) souriant(e) et motivé(e). Missions : accueil clientèle, conseil, gestion du stock et tenue de caisse.",
    location: "85 Rue Sainte-Catherine, 33000 Bordeaux",
    startDate: "2026-05-15",
    endDate: "2026-07-15",
    hourlyRate: 12.00,
    nbPositions: 1,
    latitude: 44.8378,
    longitude: -0.5753,
    requiredSkills: ["Vente", "Accueil", "Caisse"],
    schedules: {
      mardi: { start: "10:00", end: "19:00" },
      mercredi: { start: "10:00", end: "19:00" },
      samedi: { start: "09:00", end: "18:00" },
    },
    jobType: "Commerce",
    status: "ACTIVE",
    companyName: "Mode & Style",
    logoUrl: null,
    activityType: "COMMERCE",
    isDemo: true,
  },
  {
    id: "demo-3",
    title: "Agent de sécurité événementiel",
    description:
      "Pour nos événements estivaux (concerts, festivals, soirées), nous recrutons des agents de sécurité. Présence requise sur les entrées et les espaces VIP au Hangar 14.",
    location: "Hangar 14, Quai Louis XVIII, 33000 Bordeaux",
    startDate: "2026-06-15",
    endDate: "2026-09-15",
    hourlyRate: 14.50,
    nbPositions: 5,
    latitude: 44.8437,
    longitude: -0.5667,
    requiredSkills: ["Accueil", "Communication"],
    schedules: {
      vendredi: { start: "19:00", end: "02:00" },
      samedi: { start: "19:00", end: "03:00" },
    },
    jobType: "Événementiel",
    status: "ACTIVE",
    companyName: "Sécur'Events",
    logoUrl: null,
    activityType: "EVENEMENTIEL",
    isDemo: true,
  },
  {
    id: "demo-4",
    title: "Livreur(se) à vélo",
    description:
      "Rejoins notre équipe de livreurs pour la livraison de repas à domicile dans Bordeaux. Tu es autonome, ponctuel(le) et tu connais bien la ville. Vélo électrique fourni.",
    location: "Place de la Victoire, 33000 Bordeaux",
    startDate: "2026-05-20",
    endDate: "2026-08-20",
    hourlyRate: 12.50,
    nbPositions: 3,
    latitude: 44.8304,
    longitude: -0.5737,
    requiredSkills: ["Conduite", "Communication"],
    schedules: {
      lundi: { start: "11:30", end: "14:30" },
      mercredi: { start: "11:30", end: "14:30" },
      vendredi: { start: "18:00", end: "22:00" },
      samedi: { start: "18:00", end: "22:00" },
    },
    jobType: "Livraison",
    status: "ACTIVE",
    companyName: "VéloGironde",
    logoUrl: null,
    activityType: "SERVICES",
    isDemo: true,
  },
  {
    id: "demo-5",
    title: "Commis de cuisine",
    description:
      "Notre brasserie du port recherche un commis de cuisine pour la saison d'été. Aide à la préparation des plats, plonge et nettoyage des espaces de travail dans une ambiance conviviale.",
    location: "40 Quai de la Paludate, 33800 Bordeaux",
    startDate: "2026-06-01",
    endDate: "2026-09-01",
    hourlyRate: 12.0,
    nbPositions: 2,
    latitude: 44.8278,
    longitude: -0.5603,
    requiredSkills: ["Cuisine", "Manutention"],
    schedules: {
      mardi: { start: "09:00", end: "15:00" },
      jeudi: { start: "09:00", end: "15:00" },
      samedi: { start: "09:00", end: "15:00" },
      dimanche: { start: "09:00", end: "15:00" },
    },
    jobType: "Restauration",
    status: "ACTIVE",
    companyName: "La Brasserie du Port",
    logoUrl: null,
    activityType: "RESTAURATION",
    isDemo: true,
  },
];
