import type { Offer } from "./storage";

export const DEMO_OFFERS: Offer[] = [
  {
    id: "demo-1",
    title: "Serveur / Serveuse",
    description:
      "Nous recherchons un(e) serveur(se) dynamique pour renforcer notre équipe le week-end. Vous assurez l'accueil des clients, la prise de commandes et le service en salle dans notre bistrot parisien.",
    location: "12 Rue de Rivoli, 75001 Paris",
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    hourlyRate: 12.5,
    nbPositions: 2,
    latitude: 48.8574,
    longitude: 2.3466,
    requiredSkills: ["Service en salle", "Accueil"],
    schedules: {
      vendredi: { start: "18:00", end: "23:00" },
      samedi: { start: "12:00", end: "23:00" },
      dimanche: { start: "12:00", end: "17:00" },
    },
    jobType: "Restauration",
    status: "ACTIVE",
    companyName: "Bistrot du Louvre",
    logoUrl: null,
    activityType: "RESTAURATION",
    isDemo: true,
  },
  {
    id: "demo-2",
    title: "Vendeur(se) en boutique",
    description:
      "Pour notre boutique de prêt-à-porter, nous cherchons un(e) vendeur(se) souriant(e) et motivé(e). Missions : accueil clientèle, conseil, gestion du stock et tenue de caisse.",
    location: "45 Rue du Commerce, 75015 Paris",
    startDate: "2026-05-15",
    endDate: "2026-07-15",
    hourlyRate: 11.88,
    nbPositions: 1,
    latitude: 48.8462,
    longitude: 2.2936,
    requiredSkills: ["Vente", "Accueil", "Caisse"],
    schedules: {
      mardi: { start: "10:00", end: "19:00" },
      mercredi: { start: "10:00", end: "19:00" },
      samedi: { start: "09:00", end: "18:00" },
    },
    jobType: "Commerce",
    status: "ACTIVE",
    companyName: "Mode & Style",
    logoUrl: null,
    activityType: "COMMERCE",
    isDemo: true,
  },
  {
    id: "demo-3",
    title: "Agent de sécurité événementiel",
    description:
      "Pour nos événements estivaux (concerts, festivals, soirées), nous recrutons des agents de sécurité. Présence requise sur les entrées et les espaces VIP.",
    location: "Accor Arena, 8 Bd de Bercy, 75012 Paris",
    startDate: "2026-06-15",
    endDate: "2026-09-15",
    hourlyRate: 14.0,
    nbPositions: 5,
    latitude: 48.8382,
    longitude: 2.3784,
    requiredSkills: ["Accueil", "Communication"],
    schedules: {
      vendredi: { start: "19:00", end: "02:00" },
      samedi: { start: "19:00", end: "03:00" },
    },
    jobType: "Événementiel",
    status: "ACTIVE",
    companyName: "Sécur'Events",
    logoUrl: null,
    activityType: "EVENEMENTIEL",
    isDemo: true,
  },
  {
    id: "demo-4",
    title: "Livreur(se) à vélo",
    description:
      "Rejoins notre équipe de livreurs pour la livraison de repas à domicile dans Paris. Tu es autonome, ponctuel(le) et tu connais bien la capitale. Vélo fourni si besoin.",
    location: "10 Rue des Martyrs, 75009 Paris",
    startDate: "2026-05-20",
    endDate: "2026-08-20",
    hourlyRate: 13.0,
    nbPositions: 3,
    latitude: 48.882,
    longitude: 2.3389,
    requiredSkills: ["Conduite", "Communication"],
    schedules: {
      lundi: { start: "11:30", end: "14:30" },
      mercredi: { start: "11:30", end: "14:30" },
      vendredi: { start: "18:00", end: "22:00" },
      samedi: { start: "18:00", end: "22:00" },
    },
    jobType: "Livraison",
    status: "ACTIVE",
    companyName: "VéloRapide",
    logoUrl: null,
    activityType: "SERVICES",
    isDemo: true,
  },
  {
    id: "demo-5",
    title: "Commis de cuisine",
    description:
      "Notre restaurant gastronomique recherche un commis de cuisine pour la saison d'été. Aide à la préparation des entrées et desserts, plonge et nettoyage des espaces de travail.",
    location: "3 Place du Trocadéro, 75016 Paris",
    startDate: "2026-06-01",
    endDate: "2026-09-01",
    hourlyRate: 12.0,
    nbPositions: 2,
    latitude: 48.8638,
    longitude: 2.2899,
    requiredSkills: ["Cuisine", "Manutention"],
    schedules: {
      mardi: { start: "09:00", end: "15:00" },
      jeudi: { start: "09:00", end: "15:00" },
      samedi: { start: "09:00", end: "15:00" },
      dimanche: { start: "09:00", end: "15:00" },
    },
    jobType: "Restauration",
    status: "ACTIVE",
    companyName: "Le Trocadéro Gourmet",
    logoUrl: null,
    activityType: "RESTAURATION",
    isDemo: true,
  },
];
